/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microsql.view;

import javax.swing.table.DefaultTableModel;
import microsql.model.ParseModel;
import microsql.model.TableFormat;

/**
 *
 * @author Irwansyah
 */
public class ParsingResultFrame extends javax.swing.JFrame {
    ParseModel parseModel;
    /**
     * Creates new form ParsingResultFrame
     * @param parseModel
     */
    public ParsingResultFrame(ParseModel parseModel) {
        this.parseModel = parseModel;
        initComponents();
        parsedQueryTextArea.setText(parseModel.getQuery());
        int i = 0;
        DefaultTableModel resultTableModel = (DefaultTableModel) resultTable.getModel();
        for (TableFormat tableFormat : parseModel.getListTableFormat()) {
            resultTableModel.addRow(new Object[]{"","",""});
            resultTable.setValueAt(tableFormat.getString(), i, 0);
            resultTable.setValueAt(tableFormat.getBesaranLexic(), i, 1);
            resultTable.setValueAt(tableFormat.getTokenLexic(), i, 2);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        parsedQueryTextArea = new javax.swing.JTextArea();
        isValidTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "String", "Beseran Lexic", "Token Lexic"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(resultTable);

        parsedQueryTextArea.setEditable(false);
        parsedQueryTextArea.setBackground(new java.awt.Color(241, 240, 240));
        parsedQueryTextArea.setColumns(20);
        parsedQueryTextArea.setRows(5);
        jScrollPane1.setViewportView(parsedQueryTextArea);

        isValidTF.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(isValidTF))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isValidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField isValidTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea parsedQueryTextArea;
    private javax.swing.JTable resultTable;
    // End of variables declaration//GEN-END:variables
}
